services:
  #web:
  #  build:
  #    context: .
  #  command: sh -c "make run"
  #  ports:
  #    - "8000:8000"
  #  env_file:
  #    - .env.prod
  #  environment:
  #    - DJANGO_SETTINGS_MODULE=pollen_forecast.djangoserver.meteopollen.settings.prod
  #  depends_on:
  #    - db
  #  networks:
  #    - django_network

  #migrate:
  #  profiles: ["migrate"]
  #  build:
  #    context: .
  #  entrypoint: ["/entrypoint.migrate.sh"]
  #  env_file:
  #    - .env.prod
  #  environment:
  #    - DJANGO_SETTINGS_MODULE=pollen_forecast.djangoserver.meteopollen.settings.prod
  #  depends_on:
  #    - db
  #  networks:
  #    - django_network

  db:
    image: postgis/postgis:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    networks:
      - django_network
    ports:
      - 5433:5432
    
  redis:
    image: 'redis:alpine'
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge
