# Generated by Django 5.1.7 on 2025-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_department_name', models.CharField(help_text='The official name of the department.', max_length=255)),
                ('official_city_name', models.CharField(help_text='The official name of the city.', max_length=255)),
                ('latitude', models.FloatField(help_text='The latitude of the city.')),
                ('longitude', models.FloatField(help_text='The longitude of the city.')),
                ('is_prefecture', models.BooleanField(help_text='Indicates if the city is a prefecture.')),
            ],
        ),
    ]
