# Generated by Django 5.1.7 on 2025-03-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityforecast', '0002_pollenconcentrationforecasted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pollenconcentrationforecasted',
            index=models.Index(fields=['cityname', 'forecasted_at', 'pollen_type'], name='cityforecas_citynam_e154ca_idx'),
        ),
    ]
