# Generated by Django 5.1.7 on 2025-03-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityforecast', '0003_pollenconcentrationforecasted_cityforecas_citynam_e154ca_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the departement', max_length=255)),
                ('coordinates', models.TextField(help_text='Serealised of the liste fo the points', verbose_name='Coordinate of the shape of the departement')),
                ('code', models.CharField(help_text='The Code of the departement', max_length=4)),
            ],
        ),
    ]
