# Generated by Django 5.1.7 on 2025-03-26 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityforecast', '0004_departements'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pollenconcentrationforecasted',
            name='cityforecas_citynam_e154ca_idx',
        ),
        migrations.RemoveField(
            model_name='pollenconcentrationforecasted',
            name='cityname',
        ),
        migrations.AddField(
            model_name='city',
            name='departement',
            field=models.ForeignKey(default=None, help_text='The department to which the city belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cityforecast.departements'),
        ),
        migrations.AddField(
            model_name='pollenconcentrationforecasted',
            name='city',
            field=models.ForeignKey(default=None, help_text='The city for which the pollen forecast is made.', on_delete=django.db.models.deletion.CASCADE, related_name='pollen_forecasts', to='cityforecast.city'),
        ),
        migrations.AddIndex(
            model_name='pollenconcentrationforecasted',
            index=models.Index(fields=['city', 'forecasted_at', 'pollen_type'], name='cityforecas_city_id_cada31_idx'),
        ),
    ]
