# Generated by Django 5.1.7 on 2025-03-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityforecast', '0005_remove_pollenconcentrationforecasted_cityforecas_citynam_e154ca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departements',
            name='geometry_type',
            field=models.CharField(default='', help_text='the type of coordinate geometry', max_length=255),
        ),
        migrations.AlterField(
            model_name='pollenconcentrationforecasted',
            name='city',
            field=models.ForeignKey(default=None, help_text='The city for which the pollen forecast is made.', on_delete=django.db.models.deletion.CASCADE, related_name='pollenconcentrationforecasted', to='cityforecast.city'),
        ),
    ]
