# Generated by Django 5.1.7 on 2025-03-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityforecast', '0007_city_is_sous_prefecture_city_population_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollenConcentrationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=None, help_text='The date and time for which the forecast is valid.')),
                ('pollen_type', models.CharField(help_text='the pollen type', max_length=255)),
                ('value', models.FloatField(default=None, verbose_name='concentration of the pollen')),
            ],
        ),
    ]
