# Generated by hand on 2025-03-28 20:27

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('cityforecast', '0008_pollenconcentrationhistory'),
    ]

    operations = [
        TrigramExtension(),
    ]
